# Generated by Django 4.2.29 on 2026-03-09 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Give your idea a short, descriptive title.', max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Describe your idea in detail. URLs will be auto-linked.', verbose_name='Description')),
                ('voice_note', models.FileField(blank=True, help_text='Record or upload a voice note for this idea.', null=True, upload_to='voices/%Y/%m/', verbose_name='Voice Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Idea',
                'verbose_name_plural': 'Ideas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdeaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='idea_images/%Y/%m/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Caption')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ideas.idea', verbose_name='Idea')),
            ],
            options={
                'verbose_name': 'Idea Image',
                'verbose_name_plural': 'Idea Images',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
